services:
  application:
    build:
      context: .
    image: imirsaburov/demo-project:1
    container_name: demo-project
    hostname: demo-project
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres-demo-project
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

    networks:
      - network

networks:
  network:
    name: "demo-project"
    driver: 'bridge'